# Generated by Django 2.2.6 on 2019-11-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busID', models.IntegerField()),
                ('startlocation', models.TextField()),
                ('destination', models.TextField()),
                ('departuretime', models.TextField()),
                ('duration', models.TimeField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
