# Generated by Django 2.2.6 on 2019-11-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0002_trips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='departuretime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='trips',
            name='duration',
            field=models.TextField(),
        ),
    ]
