# Generated by Django 2.2.6 on 2019-11-20 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0003_auto_20191118_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='userTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userTypes', models.TextField()),
            ],
        ),
    ]
