# Generated by Django 2.2.6 on 2019-11-21 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0004_usertypes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userTypes',
        ),
        migrations.AddField(
            model_name='profile',
            name='mobile',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='userTypes',
            field=models.TextField(default='default'),
        ),
    ]
