# Generated by Django 2.2.6 on 2019-11-21 22:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0005_auto_20191121_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birthdate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
