# Generated by Django 2.2.6 on 2019-11-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0009_auto_20191127_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
