# Generated by Django 2.2.6 on 2019-11-27 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0010_auto_20191127_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
    ]
