# Generated by Django 2.2.6 on 2019-11-28 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0014_contact_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='user_name',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='age',
            field=models.IntegerField(default=18),
        ),
    ]
