# Generated by Django 2.2.6 on 2019-11-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0015_auto_20191128_0015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startlocation', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('journeydate', models.DateField()),
                ('departuretime', models.TimeField()),
                ('journeytype', models.CharField(max_length=100)),
                ('numberoftickets', models.IntegerField()),
                ('bookingcode', models.IntegerField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='user_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
