# Generated by Django 2.2.6 on 2019-11-29 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0016_auto_20191128_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='bookingcode',
        ),
    ]
