# Generated by Django 2.2.6 on 2019-11-29 07:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0017_remove_bookings_bookingcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='id',
        ),
        migrations.AddField(
            model_name='bookings',
            name='bookingid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
