# Generated by Django 2.2.6 on 2019-11-29 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0021_auto_20191129_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='bookingid',
            field=models.UUIDField(default='4ed94b9d', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
